// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mult
double mult(double v1, double v2);
RcppExport SEXP _CamelUp2_0_mult(SEXP v1SEXP, SEXP v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< double >::type v2(v2SEXP);
    rcpp_result_gen = Rcpp::wrap(mult(v1, v2));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_double_cpp();

static const R_CallMethodDef CallEntries[] = {
    {"_CamelUp2_0_mult", (DL_FUNC) &_CamelUp2_0_mult, 2},
    {"_rcpp_module_boot_double_cpp", (DL_FUNC) &_rcpp_module_boot_double_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_CamelUp2_0(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
