# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Camel
#' @title Encapsulates a double
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
NULL

#' @name Die
#' @title Encapsulates a double
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
NULL

#' Multiplies two doubles
#'
#' @param v1 First value
#' @param v2 Second value
#' @return Product of v1 and v2
#' @export
RandomNum <- function(N) {
    .Call(`_CamelUp2_0_RandomNum`, N)
}

#' @name Double
#' @title Encapsulates a double
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
NULL

