# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Double
#' @title Encapsulates a double
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
NULL

#' @name Double$new
#' @title Constructs a new Double object
#' @param v A value to encapsulate
NULL

#' Multiplies two doubles
#'
#' @param v1 First value
#' @param v2 Second value
#' @return Product of v1 and v2
#' @export
mult <- function(v1, v2) {
    .Call(`_CamelUp2_0_mult`, v1, v2)
}

